//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovelTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkSlateBlue")]
        public global::System.Drawing.Color ColorBoxFormBorderLeft {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxFormBorderLeft"]));
            }
            set {
                this["ColorBoxFormBorderLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RoyalBlue")]
        public global::System.Drawing.Color ColorBoxFormBorderTop {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxFormBorderTop"]));
            }
            set {
                this["ColorBoxFormBorderTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Firebrick")]
        public global::System.Drawing.Color ColorBoxFormBorderRight {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxFormBorderRight"]));
            }
            set {
                this["ColorBoxFormBorderRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkSlateGray")]
        public global::System.Drawing.Color ColorBoxFormBorderBottom {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxFormBorderBottom"]));
            }
            set {
                this["ColorBoxFormBorderBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxBackPanel {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxBackPanel"]));
            }
            set {
                this["ColorBoxBackPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxForePanel {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxForePanel"]));
            }
            set {
                this["ColorBoxForePanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxBackMenuStrip {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxBackMenuStrip"]));
            }
            set {
                this["ColorBoxBackMenuStrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxForeMenuStrip {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxForeMenuStrip"]));
            }
            set {
                this["ColorBoxForeMenuStrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxBackToolStripMenuItem {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxBackToolStripMenuItem"]));
            }
            set {
                this["ColorBoxBackToolStripMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxForeToolStripMenuItem {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxForeToolStripMenuItem"]));
            }
            set {
                this["ColorBoxForeToolStripMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxBackToolStripPanel {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxBackToolStripPanel"]));
            }
            set {
                this["ColorBoxBackToolStripPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxForeToolStripPanel {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxForeToolStripPanel"]));
            }
            set {
                this["ColorBoxForeToolStripPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxBackToolStrip {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxBackToolStrip"]));
            }
            set {
                this["ColorBoxBackToolStrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxForeToolStrip {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxForeToolStrip"]));
            }
            set {
                this["ColorBoxForeToolStrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxBackListView {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxBackListView"]));
            }
            set {
                this["ColorBoxBackListView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxForeListView {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxForeListView"]));
            }
            set {
                this["ColorBoxForeListView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxBackPictureBox {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxBackPictureBox"]));
            }
            set {
                this["ColorBoxBackPictureBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxForePictureBox {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxForePictureBox"]));
            }
            set {
                this["ColorBoxForePictureBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxBackTextBox {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxBackTextBox"]));
            }
            set {
                this["ColorBoxBackTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxForeTextBox {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxForeTextBox"]));
            }
            set {
                this["ColorBoxForeTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxBackButton {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxBackButton"]));
            }
            set {
                this["ColorBoxBackButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxForeButton {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxForeButton"]));
            }
            set {
                this["ColorBoxForeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxBackSplitContainer {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxBackSplitContainer"]));
            }
            set {
                this["ColorBoxBackSplitContainer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxForeSplitContainer {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxForeSplitContainer"]));
            }
            set {
                this["ColorBoxForeSplitContainer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxBackProgressBar {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxBackProgressBar"]));
            }
            set {
                this["ColorBoxBackProgressBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxForeProgressBar {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxForeProgressBar"]));
            }
            set {
                this["ColorBoxForeProgressBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxBackOther {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxBackOther"]));
            }
            set {
                this["ColorBoxBackOther"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ColorBoxForeOther {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxForeOther"]));
            }
            set {
                this["ColorBoxForeOther"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int IntUDFormBorderWidth {
            get {
                return ((int)(this["IntUDFormBorderWidth"]));
            }
            set {
                this["IntUDFormBorderWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckBoxFormBorderLeft {
            get {
                return ((bool)(this["CheckBoxFormBorderLeft"]));
            }
            set {
                this["CheckBoxFormBorderLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckBoxFormBorderTop {
            get {
                return ((bool)(this["CheckBoxFormBorderTop"]));
            }
            set {
                this["CheckBoxFormBorderTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckBoxFormBorderRight {
            get {
                return ((bool)(this["CheckBoxFormBorderRight"]));
            }
            set {
                this["CheckBoxFormBorderRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckBoxFormBorderBottom {
            get {
                return ((bool)(this["CheckBoxFormBorderBottom"]));
            }
            set {
                this["CheckBoxFormBorderBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int IntUDIllustrationMinColorsLevel {
            get {
                return ((int)(this["IntUDIllustrationMinColorsLevel"]));
            }
            set {
                this["IntUDIllustrationMinColorsLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800000")]
        public int IntUDIllustrationMinNonWhiteLevel {
            get {
                return ((int)(this["IntUDIllustrationMinNonWhiteLevel"]));
            }
            set {
                this["IntUDIllustrationMinNonWhiteLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int IntUDAnalysisTaskThreadLimit {
            get {
                return ((int)(this["IntUDAnalysisTaskThreadLimit"]));
            }
            set {
                this["IntUDAnalysisTaskThreadLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float FloatUDHeadMinRate {
            get {
                return ((float)(this["FloatUDHeadMinRate"]));
            }
            set {
                this["FloatUDHeadMinRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.95")]
        public float FloatUDFooterMinRate {
            get {
                return ((float)(this["FloatUDFooterMinRate"]));
            }
            set {
                this["FloatUDFooterMinRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int IntUDIgnoreMinDetectYSize {
            get {
                return ((int)(this["IntUDIgnoreMinDetectYSize"]));
            }
            set {
                this["IntUDIgnoreMinDetectYSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int IntUDConfirmHeadGap {
            get {
                return ((int)(this["IntUDConfirmHeadGap"]));
            }
            set {
                this["IntUDConfirmHeadGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int IntUDConfirmFooterGap {
            get {
                return ((int)(this["IntUDConfirmFooterGap"]));
            }
            set {
                this["IntUDConfirmFooterGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkMagenta")]
        public global::System.Drawing.Color ColorBoxRectHead {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxRectHead"]));
            }
            set {
                this["ColorBoxRectHead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Coral")]
        public global::System.Drawing.Color ColorBoxRectBody {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxRectBody"]));
            }
            set {
                this["ColorBoxRectBody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightSkyBlue")]
        public global::System.Drawing.Color ColorBoxRectFooter {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxRectFooter"]));
            }
            set {
                this["ColorBoxRectFooter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int IntUDRectViewWidth {
            get {
                return ((int)(this["IntUDRectViewWidth"]));
            }
            set {
                this["IntUDRectViewWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130")]
        public int IntUDIllustrationMinWidth {
            get {
                return ((int)(this["IntUDIllustrationMinWidth"]));
            }
            set {
                this["IntUDIllustrationMinWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("130")]
        public int IntUDIllustrationMinHeight {
            get {
                return ((int)(this["IntUDIllustrationMinHeight"]));
            }
            set {
                this["IntUDIllustrationMinHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int IntUDIllustrationRate {
            get {
                return ((int)(this["IntUDIllustrationRate"]));
            }
            set {
                this["IntUDIllustrationRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightSkyBlue")]
        public global::System.Drawing.Color ColorBoxRectColumn {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxRectColumn"]));
            }
            set {
                this["ColorBoxRectColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorBoxRectEntityBody {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxRectEntityBody"]));
            }
            set {
                this["ColorBoxRectEntityBody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public float FloatUDEntityMinRate {
            get {
                return ((float)(this["FloatUDEntityMinRate"]));
            }
            set {
                this["FloatUDEntityMinRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public float FloatUDEntityMaxRate {
            get {
                return ((float)(this["FloatUDEntityMaxRate"]));
            }
            set {
                this["FloatUDEntityMaxRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumSpringGreen")]
        public global::System.Drawing.Color ColorBoxRectColumnRuby {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxRectColumnRuby"]));
            }
            set {
                this["ColorBoxRectColumnRuby"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGreen")]
        public global::System.Drawing.Color ColorBoxRectRuby {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxRectRuby"]));
            }
            set {
                this["ColorBoxRectRuby"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumOrchid")]
        public global::System.Drawing.Color ColorBoxRectMergeTB {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxRectMergeTB"]));
            }
            set {
                this["ColorBoxRectMergeTB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tomato")]
        public global::System.Drawing.Color ColorBoxRectMergeLR {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxRectMergeLR"]));
            }
            set {
                this["ColorBoxRectMergeLR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color ColorBoxRectSplitTop {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxRectSplitTop"]));
            }
            set {
                this["ColorBoxRectSplitTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RoyalBlue")]
        public global::System.Drawing.Color ColorBoxRectSplitMiddle {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxRectSplitMiddle"]));
            }
            set {
                this["ColorBoxRectSplitMiddle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightCoral")]
        public global::System.Drawing.Color ColorBoxRectSplitBottom {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxRectSplitBottom"]));
            }
            set {
                this["ColorBoxRectSplitBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public byte ByteUDConfirmWhiteLevel {
            get {
                return ((byte)(this["ByteUDConfirmWhiteLevel"]));
            }
            set {
                this["ByteUDConfirmWhiteLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public int IntUDOutputWidth {
            get {
                return ((int)(this["IntUDOutputWidth"]));
            }
            set {
                this["IntUDOutputWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1600")]
        public int IntUDOutputHeight {
            get {
                return ((int)(this["IntUDOutputHeight"]));
            }
            set {
                this["IntUDOutputHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int IntUDMarginLeft {
            get {
                return ((int)(this["IntUDMarginLeft"]));
            }
            set {
                this["IntUDMarginLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int IntUDMarginRight {
            get {
                return ((int)(this["IntUDMarginRight"]));
            }
            set {
                this["IntUDMarginRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int IntUDMarginTop {
            get {
                return ((int)(this["IntUDMarginTop"]));
            }
            set {
                this["IntUDMarginTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int IntUDMarginBottom {
            get {
                return ((int)(this["IntUDMarginBottom"]));
            }
            set {
                this["IntUDMarginBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int IntUDLeading {
            get {
                return ((int)(this["IntUDLeading"]));
            }
            set {
                this["IntUDLeading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public float FloatUDEntityAdjacentRate {
            get {
                return ((float)(this["FloatUDEntityAdjacentRate"]));
            }
            set {
                this["FloatUDEntityAdjacentRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NovelTool.PositionType PositionTypeBoxHead {
            get {
                return ((global::NovelTool.PositionType)(this["PositionTypeBoxHead"]));
            }
            set {
                this["PositionTypeBoxHead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NovelTool.PositionType PositionTypeBoxFooter {
            get {
                return ((global::NovelTool.PositionType)(this["PositionTypeBoxFooter"]));
            }
            set {
                this["PositionTypeBoxFooter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AliceBlue")]
        public global::System.Drawing.Color ColorBoxOutputBack {
            get {
                return ((global::System.Drawing.Color)(this["ColorBoxOutputBack"]));
            }
            set {
                this["ColorBoxOutputBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jpeg")]
        public global::NovelTool.ImageType ImageTypeBoxOutput {
            get {
                return ((global::NovelTool.ImageType)(this["ImageTypeBoxOutput"]));
            }
            set {
                this["ImageTypeBoxOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public long LongUDOutputQuality {
            get {
                return ((long)(this["LongUDOutputQuality"]));
            }
            set {
                this["LongUDOutputQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DontCare")]
        public global::System.Drawing.Imaging.PixelFormat PixelFormatBoxOutput {
            get {
                return ((global::System.Drawing.Imaging.PixelFormat)(this["PixelFormatBoxOutput"]));
            }
            set {
                this["PixelFormatBoxOutput"] = value;
            }
        }
    }
}
